# Gradle & Kotlin Memory Configuration
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Disable Incremental Compilation to avoid file lock issues
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

# AndroidX & Flutter
android.useAndroidX=true
android.enableJetifier=true
android.newDsl=false
android.builtInKotlin=false