import 'package:google_maps_flutter/google_maps_flutter.dart';

List<Map<String, dynamic>> data = [
  
  {
    "reporterName": "Hassan Ali",
    "reporterImage": "https://i.pravatar.cc/150?img=8",
    "reportDate": "2026-06-02T01:00:00",
    "image": "https://picsum.photos/400/300?8",
    "childName": "Ziad",
    "childPhone": "01177777777",
    "childAge": "50",
    "description": "Blue jacket",
    "locationName": "",
    "location": const LatLng(35.62, 31.08),
    "childStatus": "Found",
    "personType": "Adult",
  },
  
  {
    "reporterName": "Ahmed Ali",
    "reporterImage": "https://i.pravatar.cc/150?img=1",
    "reportDate": "2026-06-21T11:30:00",
    "image": "https://picsum.photos/400/300?1",
    "childName": "Ahmed",
    "childPhone": "01000000000",
    "childAge": "66",
    "description": "Wearing blue shirt",
    "locationName": "",
    "location": const LatLng(30.55, 31.01),
    "childStatus": "Missing",
    "personType": "Adult",
  },
  {
    "reporterName": "Mohamed Hassan",
    "reporterImage": "https://i.pravatar.cc/150?img=2",
    "reportDate": "2026-07-18T00:00:00",
    "image": "https://picsum.photos/400/300?2",
    "childName": "Omar",
    "childPhone": "01111111111",
    "childAge": "8",
    "description": "Wearing red jacket",
    "locationName": "",
    "location": const LatLng(30.56, 31.02),
    "childStatus": "Missing",
    "personType": "Child",
  },
  {
    "reporterName": "Sara Ahmed",
    "reporterImage": "https://i.pravatar.cc/150?img=3",
    "reportDate": "2026-07-01T05:00:00",
    "image": "https://picsum.photos/400/300?3",
    "childName": "Mariam",
    "childPhone": "01222222222",
    "childAge": "5",
    "description": "White dress and black shoes",
    "locationName": "",
    "location": const LatLng(30.57, 31.03),
    "childStatus": "Found",
    "personType": "Child",
  },
  {
    "reporterName": "Mona Adel",
    "reporterImage": "https://i.pravatar.cc/150?img=5",
    "reportDate": "2026-07-21T10:30:00",
    
    "image": "https://picsum.photos/400/300?5",
    "childName": "Laila",
    "childPhone": "01144444444",
    "childAge": "4",
    "description": "Pink clothes",
    "locationName": "",
    "location": const LatLng(30.59, 31.05),
    "childStatus": "Accident",
    "personType": "Child",
  },

];
