import 'package:google_maps_flutter/google_maps_flutter.dart';

final List<Map<String, dynamic>> data = [
  // ==================== FOUND ====================

  {
    "report_id": "1",
    "reporterName": "Omar Adel",
    "reporterImage": "https://randomuser.me/api/portraits/men/32.jpg",
    "reportDate": "2026-06-03T14:20:00",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKLnZ5qBKRAhaKp7Yd9qMKY2-lhkKaH-dAv5IbmaWBMw&s=10",
    "childName": "Youssef Ali",
    "phone": "01033333333",
    "age": "11",
    "description": "Green jacket and blue jeans. Last seen near the beach.",
    "locationName": "Alexandria",
    "location": const LatLng(31.2001, 29.9187),
    "status": "Found",
    "personType": "Child",
    "lastseen": "2026-06-03T14:10:00",
  },

  {
    "report_id": "2",
    "reporterName": "Mariam Hassan",
    "reporterImage": "https://randomuser.me/api/portraits/women/44.jpg",
    "reportDate": "2026-06-05T10:30:00",
    "image": "https://randomuser.me/api/portraits/men/15.jpg",
    "childName": "Adam Ahmed",
    "phone": "01044444444",
    "age": "27",
    "description": "Wearing a dark blue hoodie and black trousers.",
    "locationName": "Cairo",
    "location": const LatLng(30.0444, 31.2357),
    "status": "Found",
    "personType": "Adult",
    "lastseen": "2026-06-05T09:45:00",
  },

  {
    "report_id": "3",
    "reporterName": "Mahmoud Hassan",
    "reporterImage": "https://randomuser.me/api/portraits/men/68.jpg",
    "reportDate": "2026-06-07T16:15:00",
    "image": "https://randomuser.me/api/portraits/women/21.jpg",
    "childName": "Salma Mahmoud",
    "phone": "01055555555",
    "age": "14",
    "description": "Pink jacket, white shoes and carrying a small backpack.",
    "locationName": "Giza",
    "location": const LatLng(30.0131, 31.2089),
    "status": "Found",
    "personType": "Child",
    "lastseen": "2026-06-07T15:30:00",
  },

  {
    "report_id": "4",
    "reporterName": "Sara Ali",
    "reporterImage": "https://randomuser.me/api/portraits/women/65.jpg",
    "reportDate": "2026-06-08T12:00:00",
    "image": "https://randomuser.me/api/portraits/men/41.jpg",
    "childName": "Khaled Hassan",
    "phone": "01066666666",
    "age": "36",
    "description": "White shirt and blue jeans. Found safely near the station.",
    "locationName": "Menoufia",
    "location": const LatLng(30.5526, 30.9876),
    "status": "Found",
    "personType": "Adult",
    "lastseen": "2026-06-08T11:20:00",
  },

  // ==================== MISSING ====================

  {
    "report_id": "5",
    "reporterName": "Ahmed Mohamed",
    "reporterImage": "https://randomuser.me/api/portraits/men/52.jpg",
    "reportDate": "2026-06-10T09:15:00",
    "image": "https://randomuser.me/api/portraits/boys/7.jpg",
    "childName": "Malek Ahmed",
    "phone": "01122223333",
    "age": "9",
    "description": "Yellow T-shirt, black shorts and white sneakers.",
    "locationName": "Cairo",
    "location": const LatLng(30.0626, 31.2497),
    "status": "Missing",
    "personType": "Child",
    "lastseen": "2026-06-10T08:40:00",
  },

  {
    "report_id": "6",
    "reporterName": "Nour Samir",
    "reporterImage": "https://randomuser.me/api/portraits/women/33.jpg",
    "reportDate": "2026-06-11T18:25:00",
    "image": "https://randomuser.me/api/portraits/women/29.jpg",
    "childName": "Mona Samir",
    "phone": "01133334444",
    "age": "22",
    "description": "Wearing a black jacket, gray trousers and carrying a handbag.",
    "locationName": "Alexandria",
    "location": const LatLng(31.2156, 29.9553),
    "status": "Missing",
    "personType": "Adult",
    "lastseen": "2026-06-11T17:50:00",
  },

  {
    "report_id": "7",
    "reporterName": "Yasser Ibrahim",
    "reporterImage": "https://randomuser.me/api/portraits/men/75.jpg",
    "reportDate": "2026-06-13T13:40:00",
    "image": "https://randomuser.me/api/portraits/boys/18.jpg",
    "childName": "Ziad Yasser",
    "phone": "01244445555",
    "age": "7",
    "description": "Red T-shirt, blue shorts and black sandals.",
    "locationName": "Tanta",
    "location": const LatLng(30.7865, 31.0004),
    "status": "Missing",
    "personType": "Child",
    "lastseen": "2026-06-13T12:55:00",
  },

  {
    "report_id": "8",
    "reporterName": "Heba Mostafa",
    "reporterImage": "https://randomuser.me/api/portraits/women/49.jpg",
    "reportDate": "2026-06-15T20:10:00",
    "image": "https://randomuser.me/api/portraits/men/61.jpg",
    "childName": "Mostafa Adel",
    "phone": "01255556666",
    "age": "31",
    "description": "Gray hoodie, dark jeans and brown shoes.",
    "locationName": "Qalyubia",
    "location": const LatLng(30.1798, 31.2056),
    "status": "Missing",
    "personType": "Adult",
    "lastseen": "2026-06-15T19:30:00",
  },

  // ==================== ACCIDENT ====================

  {
    "report_id": "9",
    "reporterName": "Karim Hassan",
    "reporterImage": "https://randomuser.me/api/portraits/men/22.jpg",
    "reportDate": "2026-06-18T11:35:00",
    "image": "https://randomuser.me/api/portraits/men/46.jpg",
    "childName": "Amr Khaled",
    "phone": "01077778888",
    "age": "29",
    "description": "Person involved in a road accident. Wearing a blue shirt.",
    "locationName": "Cairo",
    "location": const LatLng(30.0131, 31.2556),
    "status": "Accident",
    "personType": "Adult",
    "lastseen": "2026-06-18T11:20:00",
  },

  {
    "report_id": "10",
    "reporterName": "Reem Adel",
    "reporterImage": "https://randomuser.me/api/portraits/women/57.jpg",
    "reportDate": "2026-06-19T15:45:00",
    "image": "https://randomuser.me/api/portraits/women/68.jpg",
    "childName": "Hana Adel",
    "phone": "01088889999",
    "age": "34",
    "description": "Involved in a traffic accident. Wearing a white jacket.",
    "locationName": "Giza",
    "location": const LatLng(29.9870, 31.2118),
    "status": "Accident",
    "personType": "Adult",
    "lastseen": "2026-06-19T15:30:00",
  },

  {
    "report_id": "11",
    "reporterName": "Mostafa Ali",
    "reporterImage": "https://randomuser.me/api/portraits/men/35.jpg",
    "reportDate": "2026-06-21T08:50:00",
    "image": "https://randomuser.me/api/portraits/boys/22.jpg",
    "childName": "Omar Mostafa",
    "phone": "01199990000",
    "age": "13",
    "description": "Minor involved in an accident. Wearing a green T-shirt.",
    "locationName": "Menoufia",
    "location": const LatLng(30.4667, 30.9333),
    "status": "Accident",
    "personType": "Child",
    "lastseen": "2026-06-21T08:35:00",
  },

  {
    "report_id": "12",
    "reporterName": "Dina Mahmoud",
    "reporterImage": "https://randomuser.me/api/portraits/women/76.jpg",
    "reportDate": "2026-06-23T17:20:00",
    "image": "https://randomuser.me/api/portraits/men/79.jpg",
    "childName": "Hany Mahmoud",
    "phone": "01211112222",
    "age": "41",
    "description": "Person involved in a motorcycle accident. Wearing a black jacket.",
    "locationName": "Beheira",
    "location": const LatLng(31.0341, 30.4682),
    "status": "Accident",
    "personType": "Adult",
    "lastseen": "2026-06-23T17:05:00",
  },
];