name: Build iOS Simulator

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Find Project and Build iOS Simulator
        run: |
          # البحث عن المجلد الذي يحتوي على pubspec.yaml
          PROJECT_DIR=$(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1 | xargs dirname)
          echo "Flutter project found at: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          
          # تثبيت الحزم والبناء
          flutter pub get
          flutter build ios --simulator --no-codesign
          
          # ضغط الناتج
          cd build/ios/iphonesimulator
          zip -r -y Runner.zip Runner.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-build
          path: "**/Runner.zip"
